spring.application.name=transaction-service
server.port=8082

# Connects to the Docker PostgreSQL container instance on port 5432
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_transactions
spring.datasource.username=tx_user
spring.datasource.password=tx_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Kafka Consumer Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=banking-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Trusted Packages configuration for JSON deserialization
spring.kafka.consumer.properties.spring.json.trusted.packages=*