spring.application.name=account-service
server.port=8081

# Connects to your local Oracle 21c PDB
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/PDB_BANKS
spring.datasource.username=scott
spring.datasource.password=tiger

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CORRECTED Kafka Producer Configuration for Outbox Relayer Pattern
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# Change this from JsonSerializer to StringSerializer to match KafkaTemplate<String, String>
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Tell the main thread to drop the metadata lookups fast if Kafka is down
spring.kafka.producer.properties.max.block.ms=3000

# Zero out retries so it drops immediately on error
spring.kafka.producer.retries=0

# Lower the request timeout barrier so delivery timeout math checks out perfectly
spring.kafka.producer.properties.request.timeout.ms=2000
spring.kafka.producer.properties.delivery.timeout.ms=30000

#Disabling OSIV forces Hibernate to close the database connection
# the exact moment your @Transactional service method ends.
spring.jpa.open-in-view=false